frontend/models/Comment.php
<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "comment".
 *
 * @property integer $id
 * @property integer $post_id
 * @property integer $user_id
 * @property integer $parent_id
 * @property string $text
 * @property string $created
 * @property integer $pluses_count
 * @property integer $minuses_count
 *
 * @property User $user
 * @property Post $post
 */
class Comment extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'comment';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['post_id', 'user_id', 'text'], 'required'],
            [['post_id', 'user_id', 'parent_id', 'original_parent_id', 'pluses_count', 'minuses_count'], 'integer'],
            [['text'], 'string'],
            [['text'], 'trim'],
            [['text'], 'filter', 'filter' => 'strip_tags'],
            [['created'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'post_id' => Yii::t('app', 'Post ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'parent_id' => Yii::t('app', 'Parent ID'),
            'text' => Yii::t('app', 'Text'),
            'created' => Yii::t('app', 'Created'),
            'pluses_count' => Yii::t('app', 'Pluses Count'),
            'minuses_count' => Yii::t('app', 'Minuses Count'),
        ];
    }

    /**
     * @inheritdoc
     * @return CommentQuery
     */
    public static function find()
    {
        return new CommentQuery(get_called_class());
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPost()
    {
        return $this->hasOne(Post::className(), ['id' => 'post_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChilds()
    {
       return $this->hasMany(Comment::className(), ['parent_id' => 'id']);
    }


    /**
     * ADDITIONAL FUNCTIONS HERE
     */

    /**
     * Return username of comment author
     */
    public function getAuthorName()
    {
        return $this->user->username;
    }

/*    public static function findTopComment()
    {
        return self::find()->where(['pluses_count' => 'MAX(pluses_count)'])->one();
    }*/
}

frontend/models/User.php
<?php
namespace frontend\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use yii\helpers\Url;

use dektrium\user\models\User as BaseUser;

/**
 * User model
 *
 * @property integer $id
 * @property string $username
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 *  
 * @property Post[] $favorites
 * @property Comment[] $favoriteComments
 * @property Post[] $posts
 * @property PlusMinus[] $plusMinuses
 * @property CommentPlusMinus[] $commentPlusMinuses
 * @property Profile $profile
 * @property SocialAccount[] $socialAccounts
 * @property Token[] $tokens
 * @property PlusMinus[] $pluses
 * @property PlusMinus[] $minuses
 * @property CommentPlusMinus[] $commentPluses
 * @property CommentPlusMinus[] $commentMinuses
 * @property Comment[] $comments
 */
class User extends BaseUser implements IdentityInterface
{
    public $postAddingError;

    private $_pluses;
    private $_minuses;
    private $_commentPluses;
    private $_commentMinuses;

    private $_favorites;
    private $_favoriteComments;

    private $_tag_subscriptions;
    private $_tag_ignores;

    private $_user_subscriptions;
    private $_user_ignores;

    public function canAddPost($type)
    {
        $maxPostsPerDay = 0;

        if($this->profile->rating >= 0)
        {
            $maxPostsPerDay = DEFAULT_POSTS_PER_DAY;

            if($this->profile->rating > THIRD_LEVEL_RATING)
                $maxPostsPerDay = THIRD_LEVEL_POSTS_PER_DAY;
        }
        else
        {
            $this->postAddingError = Yii::t('app', 'You can not add any posts (<0).');
            return false;
        }

        if($this->todayPostsCount() >= $maxPostsPerDay)
        {
            $this->postAddingError = Yii::t('app', 'Today posts limit is empty ({0, number})', $maxPostsPerDay);
            return false;
        }

        return true;
    }

    public function canAddComment()
    {
        if($this->profile->rating <= FIRST_SUBLEVEL_RATING)
            return false;

        return true;
    }

    public function canRate()
    {
        if($this->profile->rating <= SECOND_SUBLEVEL_RATING)
            return false;

        return true;
    }

    public function todayPostsCount()
    {
        return Post::find()
            ->where('careated_date = CURDATE()')
            ->andWhere(['user_id' => $this->id])
            ->count();
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPlusMinuses()
    {
        return $this->hasMany(PlusMinus::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCommentPlusMinuses()
    {
        return $this->hasMany(CommentPlusMinus::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPosts()
    {
        return $this->hasMany(Post::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFavorites()
    {
        return $this->hasMany(Post::className(), ['id' => 'post_id'])
            ->viaTable('favorites', ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFavoriteComments()
    {
        return $this->hasMany(Comment::className(), ['id' => 'comment_id'])
            ->viaTable('favorite_comments', ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
       return $this->hasMany(Comment::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTagSubscriptions()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
            ->viaTable('tag_subscription', ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTagIgnores()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])
            ->viaTable('tag_ignore', ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserSubscriptions()
    {
        return $this->hasMany(User::className(), ['id' => 'user_id'])
            ->viaTable('user_subscription', ['follower_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserIgnores()
    {
        return $this->hasMany(User::className(), ['id' => 'ignored_id'])
            ->viaTable('user_ignore', ['user_id' => 'id']);
    }

    public function getPluses()
    {
         if($this->_pluses == null)
             $this->processPlusesMinuses();
 
         return $this->_pluses;
    }

   public function getMinuses()
   {
        if($this->_minuses == null)
            $this->processPlusesMinuses();

        return $this->_minuses;
   }

   public function getCommentPluses()
    {
         if($this->_commentPluses == null)
             $this->processCommentPlusesMinuses();
 
         return $this->_commentPluses;
    }

   public function getCommentMinuses()
   {
        if($this->_commentMinuses == null)
            $this->processCommentPlusesMinuses();

        return $this->_commentMinuses;
   }

    private function processPlusesMinuses()
    {
         $this->_pluses = [];
         $this->_minuses = [];

         foreach ($this->plusMinuses as $pm) 
         {
             if($pm->sign == 'plus')
                 $this->_pluses[$pm->post_id] = $pm;
             elseif($pm->sign == 'minus')
                 $this->_minuses[$pm->post_id] = $pm;
         }
    }

    private function processCommentPlusesMinuses()
    {
         $this->_commentPluses = [];
         $this->_commentMinuses = [];

         foreach ($this->commentPlusMinuses as $pm) 
         {
             if($pm->sign == 'plus')
                 $this->_commentPluses[$pm->comment_id] = $pm;
             elseif($pm->sign == 'minus')
                 $this->_commentMinuses[$pm->comment_id] = $pm;
         }
    }

    public function getUserFavorites()
    {
         if($this->_favorites == null)
             $this->processFavorites();
 
         return $this->_favorites;
    }

    public function getUserTagSubscriptions()
    {
         if($this->_tag_subscriptions == null)
             $this->processTagSubscriptions();
 
         return $this->_tag_subscriptions;
    }

    public function getUserTagIgnores()
    {
         if($this->_tag_ignores == null)
             $this->processTagIgnores();
 
         return $this->_tag_ignores;
    }

    public function getUserUserSubscriptions()
    {
         if($this->_user_subscriptions == null)
             $this->processUserSubscriptions();
 
         return $this->_user_subscriptions;
    }

    public function getUserUserIgnores()
    {
         if($this->_user_ignores == null)
             $this->processUserIgnores();
 
         return $this->_user_ignores;
    }

    public function getUserFavoriteComments()
    {
         if($this->_favoriteComments == null)
             $this->processFavoriteComments();
 
         return $this->_favoriteComments;
    }

    public function getProfileUrl()
    {
        return Url::to(['/profile/user', 'id' => $this->id]);
    }

    public function getAvaUrl()
    {
        return '/img/img_3.png';
    }

    public function getRatedPosts()
    {
        $uid = $this->id;

        return Post::find()
            ->join('RIGHT JOIN', 'plus_minus', "post.id = plus_minus.post_id AND plus_minus.user_id = $uid");
    }

    private function processFavorites()
    {
        $this->_favorites = [];

        foreach ($this->favorites as $f)
            $this->_favorites[$f->id] = $f;
    }

    private function processFavoriteComments()
    {
        $this->_favoriteComments = [];

        foreach ($this->favoriteComments as $f)
            $this->_favoriteComments[$f->id] = $f;
    }

    private function processTagSubscriptions()
    {
        $this->_tag_subscriptions = [];

        foreach ($this->tagSubscriptions as $t)
            $this->_tag_subscriptions[$t->id] = $t;
    }

    private function processTagIgnores()
    {
        $this->_tag_ignores = [];

        foreach ($this->tagIgnores as $t)
            $this->_tag_ignores[$t->id] = $t;
    }

    private function processUserSubscriptions()
    {
        $this->_user_subscriptions = [];

        foreach ($this->userSubscriptions as $t)
            $this->_user_subscriptions[$t->user_id] = $t;
    }

    private function processUserIgnores()
    {
        $this->_user_ignores = [];

        foreach ($this->userIgnores as $t)
            $this->_user_ignores[$t->ignored_id] = $t;
    }


}

frontend/controllers/CommentController.php
<?php

namespace frontend\controllers;

use frontend\models\Comment;
use yii\web\Response;
use yii\widgets\ActiveForm;
use frontend\models\FavoriteComments;
use frontend\models\CommentPlusMinus;

class CommentController extends \yii\web\Controller
{
    public $layout = 'empty';

    public function actionCompose()
    {
        if(\Yii::$app->user->isGuest || !\Yii::$app->user->identity->canAddComment())
            return null;

        $model = new Comment();

        $model->user_id = \Yii::$app->user->id;
        $model->post_id = (int)\Yii::$app->request->get('post_id');

        if( $this->performAjaxValidation($model) )
        {
            if(\Yii::$app->request->post('ajax') == null)
                if ($model->load(\Yii::$app->request->post()))
                {
                    if ($model->validate()) 
                    {
                        $model->save();
                        echo json_encode(['success' => true, 'id'=>$model->id]);
                        \Yii::$app->end();
                    }
                }
        }

        return $this->renderAjax('compose', [
            'model' => $model,
        ]);
    }

    public function actionPlusMinus($comment_id, $sign)
    {
        $response = ['success' => false, 'pluses' => 0, 'minuses' => 0];

        if(in_array($sign, ['plus', 'minus']) && \Yii::$app->user->identity->canRate())
        {
            $plusMinus = CommentPlusMinus::find()
                ->where(['comment_id' => (int)$comment_id, 'user_id' => \Yii::$app->user->id])
                ->one();

            if($plusMinus)
                $plusMinus->delete();

            $plusMinus = new CommentPlusMinus;
            $plusMinus->comment_id = (int)$comment_id;
            $plusMinus->user_id = \Yii::$app->user->id;
            $plusMinus->sign = $sign;

            if($plusMinus->validate())
                try 
                {
                    $plusMinus->save();
                    $response['success'] = true;
                }
                catch (Exception $e)
                {}

            //get comment plus and minus values after update
            $comment = Comment::findOne($comment_id);
            if($comment)
            {
                $response['pluses'] = $comment->pluses_count;
                $response['minuses'] = $comment->minuses_count;
            }
        }

        echo json_encode($response);
    }

    public function actionAddToFavorites($comment_id)
    {
        $response = ['success' => false];

        $favorite = FavoriteComments::find()
            ->where(['comment_id' => (int)$comment_id, 'user_id' => \Yii::$app->user->id])
            ->one();

        if(!$favorite)
        {
            $favorite = new FavoriteComments;
            $favorite->comment_id = (int)$comment_id;
            $favorite->user_id = \Yii::$app->user->id;

            if($favorite->validate())
                try 
                {
                    $favorite->save();
                    $response['success'] = true;
                }
                catch (Exception $e)
                {}
        }

        echo json_encode($response);
    }

    /**
    * Performs ajax validation.
    * @param Model $model
    * @throws \yii\base\ExitException
    */
    protected function performAjaxValidation(Comment $model)
    {
        if (\Yii::$app->request->isAjax && $model->load(\Yii::$app->request->post())) {
            \Yii::$app->response->format = Response::FORMAT_JSON;
            
            $errors = ActiveForm::validate($model);
            if($model->hasErrors()) {
                echo json_encode($errors);
                \Yii::$app->end();
            }

            return true;
        }
    }

}

frontend/views/comment/comment.php
<?php 
use \yii\timeago\TimeAgo;
use yii\helpers\Url;

 ?>

                <a href="<?=$comment->user->profileUrl?>" class="ava_user_post">

                    <!-- @TODO: add user ava and url (create method User::getProfileUrl()) -->
                    <div class="ava_user_post_man">
                        <img src="/img/ava_post.png">
                    </div>
                </a>

                <div class="info_comment" id="comment-<?=$comment->id?>">
                    <p class="name_user">

                        <!-- //@TODO: prfile url, $post::authorName() -->
                        <a href="<?=$comment->user->profileUrl?>"><?=$comment->authorName?></a>
                    </p>

                    <div class="info_post_more clearfix">
                        <span class="time_add_post point_after">
                            <img src="/img/time_icon.png"><?= TimeAgo::widget(['timestamp' => $comment->created]); ?></span>                                           

                        <?php
                            $dis = true;
                            if (!\Yii::$app->user->isGuest)
                            {
                                $dis = false;
                                if(in_array($comment->id, array_keys(\Yii::$app->user->identity->getUserFavoriteComments() )))
                                    $dis = true;
                            }
                        ?>

                        <div class="add_post_icon point_after <?php if($dis) echo 'disabled';?>" data-url="<?=Url::to(['/comment/add-to-favorites', 'comment_id' => $comment->id])?>">
                            <img src="/img/add_post.png" class="tooltip_text <?php if($dis) echo 'animate_add_post';?>" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="Зберегти">
                        </div>

                    </div>

                    <p class="text_comment"><?=$comment->text?></p>

                    <div class="down_post rating_block">
                        <div class="post_up">

                            <!-- COMMENT PLUS -->
                            <?php 
                                $dis = true;
                                if (!\Yii::$app->user->isGuest)
                                {
                                    $dis = false;
                                    if(in_array($comment->id, array_keys(\Yii::$app->user->identity->commentPluses)))
                                        $dis = true;
                                }
                            ?>

                            <div class="post_up_icon <?php if($dis) echo ' disabled '; ?>" data-url="<?=Url::to(['/comment/plus-minus', 'comment_id' => $comment->id, 'sign' => 'plus'])?>"></div>

                            <span class="plus-counter">+<?=$comment->pluses_count?></span>
                        </div>
                        <div class="post_down">
                            
                            <!-- COMMENT MINUS -->
                            <?php 
                                $dis = true;
                                if (!\Yii::$app->user->isGuest)
                                {
                                    $dis = false;
                                    if(in_array($comment->id, array_keys(\Yii::$app->user->identity->commentMinuses)))
                                        $dis = true;
                                }
                            ?>

                            <div class="post_down_icon <?php if($dis) echo ' disabled '; ?>" data-url="<?=Url::to(['/comment/plus-minus', 'comment_id' => $comment->id, 'sign' => 'minus'])?>"></div>
                            
                            <span class="minus-counter">-<?=$comment->minuses_count?></span>
                        </div>

                        <?php if(count($comment->childs)): ?>
                            <span class="show_comment reply_comment" style="background-image: url(/img/arrow_hide_comment.png);">Сховати</span>
                        <?php endif ?>

                        <?php if (!\Yii::$app->user->isGuest): ?>
                            <span class="reply_comment write-comment-reply" data-origparentid="<?=$comment->id?>" data-parentid="<?=$comment->parent_id?:$comment->id?>" data-author="<?=$comment->authorName?>">Відповісти</span>
                        <?php endif ?>

                    </div>
                </div>

frontend/views/comment/compose.php
<?php
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
?>

<div class="ava_add_comment">
    <!-- //@TODO: add user's avatar here -->
    <img src="/img/ava.png">
</div>

<div class="add_comment clearfix">

    <?php $form = ActiveForm::begin([
        'id'                    => 'create-comment-form',
        'enableAjaxValidation'  => true,
        'enableClientValidation'=> true,
        'validateOnType'        => false,
        'validateOnChange'      => false,
        'validateOnBlur'        => false,
        'validateOnSubmit'      => true,
    ]); ?>

    <?=$form->field($model, 'text', ['template' => '{input}{error}', 'inputOptions' => [
            'required'      => '',
            'placeholder'   => 'Введіть текст коментаря',
            'class'         => 'form-control',
            'style'         => 'overflow: hidden; word-wrap: break-word; height: 80px;',
        ]
    ])->textarea()?>
    

    <!-- //@TODO: implement pictures adding -->
    <div class="btn_add_picture">
        <img src="/img/icon_add_picture.png">
        <input type="file" name="avatar"><br>
    </div>

    <!-- //@TODO: show user's avatar here -->
    <div class="btn_send_comment"><img src="/img/icon_send_comment.png" style="cursor:pointer;"></div>

    
    <?=$form->field($model, 'parent_id', ['template' => '{input}'])->hiddenInput()?>
    <?=$form->field($model, 'original_parent_id', ['template' => '{input}'])->hiddenInput()?>

    <?php ActiveForm::end(); ?>

</div>

<?php 
    $this->registerJS(<<<JS
    $('#create-comment-form textarea').keydown(function (e) 
    {
      if (e.ctrlKey && e.keyCode == 13) 
        $('.btn_send_comment').click();
    });
JS
                      );
 ?>